User Timeline Comparison: Compressed
========================================================

```{r imports_and_custom_funcs, echo=FALSE, results=FALSE}
library(ggplot2)
library(scales)

#Static Dates:
zone_a_ordered <- as.POSIXct(strptime("2012-10-28 07:00:00", "%Y-%m-%d %H:%M:%S"), tz="EST")


get_ggplot <-function (user) {
  data <- user
  data$TimeConvert <- as.POSIXct(strptime(data$Time, "%Y-%m-%d %H:%M:%S %z"), tz="EST")
  data$Time <- as.POSIXct(data$TimeConvert)
  
  plot <- ggplot(data, aes(x=Time, y=Action))
  
  if (!(length(unique(data$Sentiment))==1 & is.na(unique(data$Sentiment)))){
    plot <- plot + geom_text( aes( y = rep(c(60,61,62,63,64,65,66,67,68,69),1500), 
            label = Sentiment,   col=Sentiment),   size=3.5, vjust=-1, angle=10)
    }
  if (!unique(length(unique(data$Preparation))==1 & is.na(unique(data$Preparation)))){
    plot <- plot + geom_text( aes( y = rep(c(50,51,52,53,54,55,56,57,58,59),1500), 
            label = Preparation, col=Preparation), size=3.5, vjust=-1, angle=10)
    }
  if (!unique(length(unique(data$Environment))==1 & is.na(unique(data$Environment)))){
    plot <- plot + geom_text( aes( y = rep(c(30,31,32,33,34,35,36,37,38,39),1500), 
            label = Environment, col=Environment), size=3.5, vjust=-1, angle=10)
    }
  if (!unique(length(unique(data$Collective.Information))==1 & is.na(unique(data$Collective.Information)))){
    plot <- plot + geom_text( aes( y = rep(c(40,41,42,43,44,45,46,47,48,49),1500), 
            label=Collective.Information, col=Collective.Information), size=3.5, vjust=-1, angle=10)
    }
  if (!unique(length(unique(data$Movement))==1 & is.na(unique(data$Movement)))){
    plot <- plot + geom_text( aes( y = rep(c(20,21,22,23,24,25,26,27,28,29),1500),   
            label = Movement,    col=Movement),    size=3.5, vjust=-1, angle=10)
    }
    
  if (!unique(length(unique(data$Cluster))==1 & is.na(unique(data$Cluster)))){
    plot <- plot + geom_point( aes (y = Cluster, col = "Geo Location"))
    }
  
  #Add static data:
    plot <- plot + geom_vline(xintercept=as.numeric(zone_a_ordered), linetype="dotted", label="Evacuation Ordered")
  
  #House keeping:
    plot <- plot + theme(legend.position="none") +
                  scale_y_discrete(breaks=c(0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,30,40,50,60,69), 
                                   labels=c("0","1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19",
                                          "Geo Location", "Reported Movement", "Environment","Collective Information", 
                                          "Preparation", "Sentiment"))
                                   
                                  

  return (plot)
}

```
ajc678
```{r ajc678, echo=FALSE, warning=FALSE, fig.width=16, fig.height=5}
data = read.csv("../exports_2/ajc6789_minutes.csv", strip.white = TRUE)  # read csv file 
get_ggplot(data)

```
Matt Gunn
```{r mattgunn, echo=FALSE, warning=FALSE, fig.width=16, fig.height=5}
data = read.csv("../exports_2/mattgunn_minutes.csv")  # read csv file 
get_ggplot(data)
```
SimoMarms
```{r SimoMarms, echo=FALSE, warning=FALSE, fig.width=16, fig.height=5}
data = read.csv("../exports_2/SimoMarms_minutes.csv")  # read csv file 
get_ggplot(data)
```
jefflac
```{r jefflac, echo=FALSE, warning=FALSE, fig.width=16, fig.height=5}
data = read.csv("../exports_2/jefflac_minutes.csv")  # read csv file 
get_ggplot(data)
```
jericajazz
```{r jericajazz, echo=FALSE, warning=FALSE, fig.width=16, fig.height=5}
data = read.csv("../exports_2/jericajazz_minutes.csv")  # read csv file 
get_ggplot(data)
```
nicolelmancini
```{r nicolelmancini, echo=FALSE, warning=FALSE, fig.width=16, fig.height=5}
data = read.csv("../exports_2/nicolelmancini_minutes.csv")  # read csv file 
get_ggplot(data)
```
tlal2
```{r tlal2, echo=FALSE, warning=FALSE, fig.width=16, fig.height=5}
data = read.csv("../exports_2/tlal2_minutes.csv")  # read csv file 
get_ggplot(data)
```
BeachyIsPeachy
```{r BeachyIsPeachy, echo=FALSE, warning=FALSE, fig.width=16, fig.height=5}
data = read.csv("../exports_2/BeachyIsPeachy_minutes.csv")  # read csv file 
get_ggplot(data)
```
Max_Not_Mark
```{r Max_Not_Mark, echo=FALSE, warning=FALSE, fig.width=16, fig.height=5}
data = read.csv("../exports_2/Max_Not_Mark_minutes.csv")  # read csv file 
get_ggplot(data)
```
Rigo7x
```{r Rigo7x, echo=FALSE, warning=FALSE, fig.width=16, fig.height=5}
data = read.csv("../exports_2/Rigo7x_minutes.csv")  # read csv file 
get_ggplot(data)
```
MoazaMatar
```{r MoazaMatar, echo=FALSE, warning=FALSE, fig.width=16, fig.height=5}
data = read.csv("../exports_2/MoazaMatar_minutes.csv", strip.white = TRUE)  # read csv file 
get_ggplot(data)
```