User Timeline Comparisons
========================================================

```{r imports_and_custom_funcs, echo=FALSE, results=FALSE}
library(ggplot2)
library(scales)

#Global Vars
zone_a_ordered <- as.POSIXct(strptime("2012-10-28 07:00:00", "%Y-%m-%d %H:%M:%S"), tz="EST")

get_ggplot <-function (user) {
  data <- user
  data$TimeConvert <- as.POSIXct(strptime(data$Time, "%Y-%m-%d %H:%M:%S %z"), tz="EST")
  data$Time <- as.POSIXct(data$TimeConvert)
  
  return ( ggplot(data, aes(x=Time, y=Action)) +  
    geom_text( aes( y = rep(c(60,61,62,63,64,65,66,67,68,69),1500), 
            label = Sentiment,   col=Sentiment),   size=3.5, vjust=-1, angle=10) +
    geom_text( aes( y = rep(c(50,51,52,53,54,55,56,57,58,59),1500), 
            label = Preparation, col=Preparation), size=3.5, vjust=-1, angle=10) +
    geom_text( aes( y = rep(c(30,31,32,33,34,35,36,37,38,39),1500), 
            label = Environment, col=Environment), size=3.5, vjust=-1, angle=10) +
    geom_text( aes( y = rep(c(40,41,42,43,44,45,46,47,48,49),1500), 
            label=Collective.Information, col=Collective.Information), size=3.5, vjust=-1, angle=10) +
    geom_text( aes( y = rep(c(20,21,22,23,24,25,26,27,28,29),1500),    
            label = Movement,    col=Movement),    size=3.5, vjust=-1, angle=10) +
    geom_point(aes(y = Cluster, col = "Geo Location")) + 
    #Add the storm lines:
    geom_vline(xintercept=as.numeric(zone_a_ordered), linetype="dotted", label="Evacuation Ordered") +
     
      #housekeeping
      theme(legend.position="none")+
      scale_y_discrete(breaks=c(0,20,30,40,50,60,69), labels=c("","Geo Location", "Reported Movement", 
                                  "Environment","Collective Information", "Preparation", "Sentiment"))
   ) 
}

```

## ajc678
```{r ajc678, echo=FALSE, warning=FALSE, fig.width=16, fig.height=10}
data = read.csv("../exports_2/ajc6789_minutes.csv")  # read csv file 
get_ggplot(data)

```

## Matt Gunn
```{r mattgunn, echo=FALSE, warning=FALSE, fig.width=16, fig.height=10}
data = read.csv("../exports_2/mattgunn_minutes.csv")  # read csv file 
get_ggplot(data)
```

