# Site settings
title: "Predicting Evacuation and Migration Behavior during Crisis with Twitter"
email: "jennings.anderson@colorado.edu"
description: "2014 Research project with Project EPIC and the National Center for Atmospheric Research."
baseurl: "/Twitter-Evacuation-Patterns"
url: "jenningsanderson.github.io"

data_source: 'datasets'

# Build settings
# markdown: redcarpet
# extensions: [fenced_code_blocks]

#twitter: "JenningsAtCU"
github: "jenningsanderson"
